[package]
name = "benchmark_pure_revm"
version = "0.1.0"
edition = "2021"

[workspace]

[[bin]]
name = "benchmark"
path = "src/main.rs"

[dependencies]
revm = { path = "../../../revm" }
hex = "0.4"
alloy-primitives = "0.8"
alloy-sol-types = "0.8"
tokio = { version = "1.0", features = ["full"] } 